// ─────────────────────────────────────────────────────────────────────────
// ITU-T calling codes, so any hospital anywhere can record a phone number in
// its own country's format rather than the app assuming a single country.
// This is reference data only (no business logic) — kept in the domain
// layer because both the UI (components/forms) and validation
// (domain/validation.ts) need it, and neither should depend on the other.
// ─────────────────────────────────────────────────────────────────────────

export interface CountryCode {
  /** ISO 3166-1 alpha-2 code, used as the option value. */
  iso: string;
  name: string;
  /** E.164 calling code, including the leading "+". */
  dialCode: string;
}

export const DEFAULT_COUNTRY_ISO = "IN";

// Sorted by country name. Not exhaustive to the last micro-territory, but
// covers every country likely to run a hospital deployment of this app.
export const COUNTRY_CODES: CountryCode[] = [
  { iso: "AF", name: "Afghanistan", dialCode: "+93" },
  { iso: "AL", name: "Albania", dialCode: "+355" },
  { iso: "DZ", name: "Algeria", dialCode: "+213" },
  { iso: "AR", name: "Argentina", dialCode: "+54" },
  { iso: "AM", name: "Armenia", dialCode: "+374" },
  { iso: "AU", name: "Australia", dialCode: "+61" },
  { iso: "AT", name: "Austria", dialCode: "+43" },
  { iso: "AZ", name: "Azerbaijan", dialCode: "+994" },
  { iso: "BD", name: "Bangladesh", dialCode: "+880" },
  { iso: "BY", name: "Belarus", dialCode: "+375" },
  { iso: "BE", name: "Belgium", dialCode: "+32" },
  { iso: "BJ", name: "Benin", dialCode: "+229" },
  { iso: "BT", name: "Bhutan", dialCode: "+975" },
  { iso: "BO", name: "Bolivia", dialCode: "+591" },
  { iso: "BA", name: "Bosnia and Herzegovina", dialCode: "+387" },
  { iso: "BW", name: "Botswana", dialCode: "+267" },
  { iso: "BR", name: "Brazil", dialCode: "+55" },
  { iso: "BG", name: "Bulgaria", dialCode: "+359" },
  { iso: "BF", name: "Burkina Faso", dialCode: "+226" },
  { iso: "BI", name: "Burundi", dialCode: "+257" },
  { iso: "KH", name: "Cambodia", dialCode: "+855" },
  { iso: "CM", name: "Cameroon", dialCode: "+237" },
  { iso: "CA", name: "Canada", dialCode: "+1" },
  { iso: "CF", name: "Central African Republic", dialCode: "+236" },
  { iso: "TD", name: "Chad", dialCode: "+235" },
  { iso: "CL", name: "Chile", dialCode: "+56" },
  { iso: "CN", name: "China", dialCode: "+86" },
  { iso: "CO", name: "Colombia", dialCode: "+57" },
  { iso: "CD", name: "Congo (DRC)", dialCode: "+243" },
  { iso: "CR", name: "Costa Rica", dialCode: "+506" },
  { iso: "HR", name: "Croatia", dialCode: "+385" },
  { iso: "CU", name: "Cuba", dialCode: "+53" },
  { iso: "CY", name: "Cyprus", dialCode: "+357" },
  { iso: "CZ", name: "Czech Republic", dialCode: "+420" },
  { iso: "DK", name: "Denmark", dialCode: "+45" },
  { iso: "DJ", name: "Djibouti", dialCode: "+253" },
  { iso: "DO", name: "Dominican Republic", dialCode: "+1" },
  { iso: "EC", name: "Ecuador", dialCode: "+593" },
  { iso: "EG", name: "Egypt", dialCode: "+20" },
  { iso: "SV", name: "El Salvador", dialCode: "+503" },
  { iso: "EE", name: "Estonia", dialCode: "+372" },
  { iso: "ET", name: "Ethiopia", dialCode: "+251" },
  { iso: "FJ", name: "Fiji", dialCode: "+679" },
  { iso: "FI", name: "Finland", dialCode: "+358" },
  { iso: "FR", name: "France", dialCode: "+33" },
  { iso: "GA", name: "Gabon", dialCode: "+241" },
  { iso: "GM", name: "Gambia", dialCode: "+220" },
  { iso: "GE", name: "Georgia", dialCode: "+995" },
  { iso: "DE", name: "Germany", dialCode: "+49" },
  { iso: "GH", name: "Ghana", dialCode: "+233" },
  { iso: "GR", name: "Greece", dialCode: "+30" },
  { iso: "GT", name: "Guatemala", dialCode: "+502" },
  { iso: "GN", name: "Guinea", dialCode: "+224" },
  { iso: "HT", name: "Haiti", dialCode: "+509" },
  { iso: "HN", name: "Honduras", dialCode: "+504" },
  { iso: "HK", name: "Hong Kong", dialCode: "+852" },
  { iso: "HU", name: "Hungary", dialCode: "+36" },
  { iso: "IS", name: "Iceland", dialCode: "+354" },
  { iso: "IN", name: "India", dialCode: "+91" },
  { iso: "ID", name: "Indonesia", dialCode: "+62" },
  { iso: "IR", name: "Iran", dialCode: "+98" },
  { iso: "IQ", name: "Iraq", dialCode: "+964" },
  { iso: "IE", name: "Ireland", dialCode: "+353" },
  { iso: "IL", name: "Israel", dialCode: "+972" },
  { iso: "IT", name: "Italy", dialCode: "+39" },
  { iso: "CI", name: "Ivory Coast", dialCode: "+225" },
  { iso: "JM", name: "Jamaica", dialCode: "+1" },
  { iso: "JP", name: "Japan", dialCode: "+81" },
  { iso: "JO", name: "Jordan", dialCode: "+962" },
  { iso: "KZ", name: "Kazakhstan", dialCode: "+7" },
  { iso: "KE", name: "Kenya", dialCode: "+254" },
  { iso: "KW", name: "Kuwait", dialCode: "+965" },
  { iso: "KG", name: "Kyrgyzstan", dialCode: "+996" },
  { iso: "LA", name: "Laos", dialCode: "+856" },
  { iso: "LV", name: "Latvia", dialCode: "+371" },
  { iso: "LB", name: "Lebanon", dialCode: "+961" },
  { iso: "LS", name: "Lesotho", dialCode: "+266" },
  { iso: "LR", name: "Liberia", dialCode: "+231" },
  { iso: "LY", name: "Libya", dialCode: "+218" },
  { iso: "LT", name: "Lithuania", dialCode: "+370" },
  { iso: "LU", name: "Luxembourg", dialCode: "+352" },
  { iso: "MO", name: "Macau", dialCode: "+853" },
  { iso: "MG", name: "Madagascar", dialCode: "+261" },
  { iso: "MW", name: "Malawi", dialCode: "+265" },
  { iso: "MY", name: "Malaysia", dialCode: "+60" },
  { iso: "MV", name: "Maldives", dialCode: "+960" },
  { iso: "ML", name: "Mali", dialCode: "+223" },
  { iso: "MT", name: "Malta", dialCode: "+356" },
  { iso: "MX", name: "Mexico", dialCode: "+52" },
  { iso: "MD", name: "Moldova", dialCode: "+373" },
  { iso: "MN", name: "Mongolia", dialCode: "+976" },
  { iso: "ME", name: "Montenegro", dialCode: "+382" },
  { iso: "MA", name: "Morocco", dialCode: "+212" },
  { iso: "MZ", name: "Mozambique", dialCode: "+258" },
  { iso: "MM", name: "Myanmar", dialCode: "+95" },
  { iso: "NA", name: "Namibia", dialCode: "+264" },
  { iso: "NP", name: "Nepal", dialCode: "+977" },
  { iso: "NL", name: "Netherlands", dialCode: "+31" },
  { iso: "NZ", name: "New Zealand", dialCode: "+64" },
  { iso: "NI", name: "Nicaragua", dialCode: "+505" },
  { iso: "NE", name: "Niger", dialCode: "+227" },
  { iso: "NG", name: "Nigeria", dialCode: "+234" },
  { iso: "NO", name: "Norway", dialCode: "+47" },
  { iso: "OM", name: "Oman", dialCode: "+968" },
  { iso: "PK", name: "Pakistan", dialCode: "+92" },
  { iso: "PA", name: "Panama", dialCode: "+507" },
  { iso: "PG", name: "Papua New Guinea", dialCode: "+675" },
  { iso: "PY", name: "Paraguay", dialCode: "+595" },
  { iso: "PE", name: "Peru", dialCode: "+51" },
  { iso: "PH", name: "Philippines", dialCode: "+63" },
  { iso: "PL", name: "Poland", dialCode: "+48" },
  { iso: "PT", name: "Portugal", dialCode: "+351" },
  { iso: "QA", name: "Qatar", dialCode: "+974" },
  { iso: "RO", name: "Romania", dialCode: "+40" },
  { iso: "RU", name: "Russia", dialCode: "+7" },
  { iso: "RW", name: "Rwanda", dialCode: "+250" },
  { iso: "SA", name: "Saudi Arabia", dialCode: "+966" },
  { iso: "SN", name: "Senegal", dialCode: "+221" },
  { iso: "RS", name: "Serbia", dialCode: "+381" },
  { iso: "SL", name: "Sierra Leone", dialCode: "+232" },
  { iso: "SG", name: "Singapore", dialCode: "+65" },
  { iso: "SK", name: "Slovakia", dialCode: "+421" },
  { iso: "SI", name: "Slovenia", dialCode: "+386" },
  { iso: "SO", name: "Somalia", dialCode: "+252" },
  { iso: "ZA", name: "South Africa", dialCode: "+27" },
  { iso: "KR", name: "South Korea", dialCode: "+82" },
  { iso: "SS", name: "South Sudan", dialCode: "+211" },
  { iso: "ES", name: "Spain", dialCode: "+34" },
  { iso: "LK", name: "Sri Lanka", dialCode: "+94" },
  { iso: "SD", name: "Sudan", dialCode: "+249" },
  { iso: "SE", name: "Sweden", dialCode: "+46" },
  { iso: "CH", name: "Switzerland", dialCode: "+41" },
  { iso: "SY", name: "Syria", dialCode: "+963" },
  { iso: "TW", name: "Taiwan", dialCode: "+886" },
  { iso: "TJ", name: "Tajikistan", dialCode: "+992" },
  { iso: "TZ", name: "Tanzania", dialCode: "+255" },
  { iso: "TH", name: "Thailand", dialCode: "+66" },
  { iso: "TG", name: "Togo", dialCode: "+228" },
  { iso: "TN", name: "Tunisia", dialCode: "+216" },
  { iso: "TR", name: "Turkey", dialCode: "+90" },
  { iso: "TM", name: "Turkmenistan", dialCode: "+993" },
  { iso: "UG", name: "Uganda", dialCode: "+256" },
  { iso: "UA", name: "Ukraine", dialCode: "+380" },
  { iso: "AE", name: "United Arab Emirates", dialCode: "+971" },
  { iso: "GB", name: "United Kingdom", dialCode: "+44" },
  { iso: "US", name: "United States", dialCode: "+1" },
  { iso: "UY", name: "Uruguay", dialCode: "+598" },
  { iso: "UZ", name: "Uzbekistan", dialCode: "+998" },
  { iso: "VE", name: "Venezuela", dialCode: "+58" },
  { iso: "VN", name: "Vietnam", dialCode: "+84" },
  { iso: "YE", name: "Yemen", dialCode: "+967" },
  { iso: "ZM", name: "Zambia", dialCode: "+260" },
  { iso: "ZW", name: "Zimbabwe", dialCode: "+263" },
];

export function findCountryByIso(iso: string): CountryCode | undefined {
  return COUNTRY_CODES.find((c) => c.iso === iso);
}

export function defaultCountry(): CountryCode {
  return findCountryByIso(DEFAULT_COUNTRY_ISO) ?? COUNTRY_CODES[0];
}
